language: python
sudo: false
python: 2.7

cache:
    directories:
        - $HOME/.cache/pip

env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
    - TOXENV=pep8
    - TOXENV=docs

install:
    - pip install tox

script:
    - tox
