language: python
sudo: false
python: 2.7

cache:
    directories:
        - $HOME/.cache/pip

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pep8
    - TOX_ENV=docs

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
